# Application for new cluster (idp-project-deploy)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ABHISHEK-KUMAR-14022001/argocd-app-config.git
    targetRevision: main
    path: policy
  destination:
    server: https://34.173.0.248   # External API of new cluster
    namespace: kyverno
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3
      backoff:
        duration: 5m
        factor: 2
        maxDuration: 30m
