# Application for default cluster (minikube)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argo-application
  namespace: argocd
spec:
  project: test
  source:
    repoURL: https://github.com/ABHISHEK-KUMAR-14022001/argocd-app-config.git
    targetRevision: HEAD
    path: test
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 3  # Retry up to 3 times
      backoff:
        duration: 5m  # Wait 5 minutes before retrying
        factor: 2
        maxDuration: 30m