# Application for default cluster (react-idp-app)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argo-application
  namespace: argocd
spec:
  project: test
  source:
    repoURL: https://github.com/ABHISHEK-KUMAR-14022001/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---

# Application for new cluster (idp-project-deploy)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-argo-application
  namespace: argocd
spec:
  project: deploy
  source:
    repoURL: https://github.com/ABHISHEK-KUMAR-14022001/argocd-app-config.git
    targetRevision: HEAD
    path: prod
  destination: 
    server: https://35.224.230.101   # External API of new cluster
    namespace: deployapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
