# 2️⃣ Deployment with Required `team` Label
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: abhishekkumar1402/node-app:latest
        ports:
        - containerPort: 8000

---
# 3️⃣ Service to Expose the Deployment
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-app
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
