apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: abhishekkumar1402/idp_nodeapp:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: node-app-config
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: node-app-config
            optional: true  # Prevents errors if ConfigMap is missing
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Uses ClusterIP instead of NodePort unless necessary
