apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-rollout
  namespace: deployapp
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 1m}
      - setWeight: 100
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: abhishekkumar1402/node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: deployapp
spec:
  selector:
    app: todo-app
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
